### PR TITLE
Travis/Sauce Integration

### PR DESCRIPTION
**Pull request by stdavis**
All tests (unit and functional) are passing for me using my own sauce account.

A few things that still need to be done by a contributor/owner:
- [ ] Log into https://travis-ci.org/ and turn on this repository
- [ ] Sign up for a free open sauce account at https://saucelabs.com/opensauce
- [ ] Go [here](https://docs.saucelabs.com/ci-integrations/travis-ci/#adding-credentials-for-a-public-github-repo) and generate encryption keys for travis and put them in `.travis.yml`.
- [ ] Fill in `<username>` at the top of `README.md` for the sauce test status badge.

In order to run the tests locally you will need to create `secrets.json` and define the sauce username and key (see `secrets.json.sample`).

Not sure if this is exactly the setup that you want but thought that it would be a good start for you.

Also, after struggling through this and talking with the intern guys it sounds like browserstack may be a better option. I'm going to investigate using them for one of my projects. It would be simple to switch to them at some point in the future. But for now the tests are running well on sauce.

### CODE REVIEW

**Comment by xsokev** [comment]
@sdavis - Thanks for all the work you've been doing on Dojo-Bootstrap. Especially with the testing. Can I add you as a contributor?

**Comment by stdavis** [comment]
I would be open to that. To be honest, I can't commit for the long term to this project. I'm using it currently in a single project but we are still trying to decide if we want to use this repo in our future projects, so I'm not sure how active I'll be in the future. But for the next few months at least I'm committed to helping it along.

**Comment by tomwayson** [comment]
I think it would be a great idea to add @stdavis - we'll take his help as long as we can get it.

**Comment by stdavis** [comment]
@xsokev I'm honored to be contributor. Thanks!

If you will log in to travis-ci.org and switch on this repo and then sign up for an open sauce account (free) and share the credentials with me then I can take care of the rest of this issue.

**Comment by stdavis** [comment]
@xsokev Any luck switching on this repo on travisci.org and signing up for an open sauce account on saucelabs.com? Only the repo owner can switch on travisci and I assume that you want to open the sauce account with your email address. If you can do these two things then I believe that I can take care of everything else to get travis to run tests for this project on sauce for every PR and commit.

**Pull request merged**
